apiVersion: apps/v1
kind: Deployment
metadata:
  name: educational-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: educational-app
  template:
    metadata:
      labels:
        app: educational-app
    spec:
      containers:
      - name: python-app
        image: stmaan/educationalcicd:latest
        ports:
        - containerPort: 80
        # --- ДОБАВЛЯЕМ ПЕРЕМЕННУЮ ---
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
