name: CI/CD with Approval

on:
  push:
    branches: [ main, staging ]

jobs:
  # --- ЗАДАЧА 1: Сборка и деплой в Staging ---
  build-and-staging:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: stmaan/educationalcicd:staging

      - name: Deploy to Staging
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config
          # Деплоим в staging всегда при пуше в любую из веток
          kubectl apply -f k8s-deployment.yml -n staging
          kubectl set image deployment/educational-app python-app=stmaan/educationalcicd:staging -n staging

  # --- ЗАДАЧА 2: Деплой в Production (с ручным одобрением) ---
  deploy-production:
    runs-on: self-hosted
    needs: build-and-staging  # Ждем завершения первой задачи
    if: github.ref == 'refs/heads/main' # Запускаем только для ветки main
    environment: production   # <--- СВЯЗКА С ТВОИМ ENV В SETTINGS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config
          # Деплоим в prod (используем тег latest или отдельный prod тег)
          kubectl apply -f k8s-deployment.yml -n production
          kubectl set image deployment/educational-app python-app=stmaan/educationalcicd:staging -n production
# Workflow with Manual Approval
